export const vehicles = [
  {
    id: 1,
    name: "Tesla Model 3",
    price: "$42,990",
    mileage: "15,234",
    image: "/tesla-model-3.png",
  },
  {
    id: 2,
    name: "BMW X5",
    price: "$59,400",
    mileage: "8,567",
    image: "/bmw-x5-luxury-suv.jpg",
  },
  {
    id: 3,
    name: "Audi A4",
    price: "$39,900",
    mileage: "22,145",
    image: "/audi-a4-sedan.jpg",
  },
  {
    id: 4,
    name: "Mercedes C-Class",
    price: "$43,550",
    mileage: "12,890",
    image: "/mercedes-c-class-luxury-sedan.jpg",
  },
  {
    id: 5,
    name: "Ford Mustang",
    price: "$27,155",
    mileage: "18,234",
    image: "/ford-mustang-sports-car.png",
  },
  {
    id: 6,
    name: "Porsche 911",
    price: "$106,100",
    mileage: "5,432",
    image: "/classic-porsche-911.png",
  },
  {
    id: 7,
    name: "Toyota RAV4",
    price: "$27,975",
    mileage: "31,567",
    image: "/toyota-rav4-suv.png",
  },
  {
    id: 8,
    name: "Honda Civic",
    price: "$23,750",
    mileage: "28,901",
    image: "/honda-civic-sedan.jpg",
  },
  {
    id: 9,
    name: "Chevrolet Camaro",
    price: "$25,000",
    mileage: "19,234",
    image: "/chevrolet-camaro-sports-car.jpg",
  },
  {
    id: 10,
    name: "Jeep Wrangler",
    price: "$30,445",
    mileage: "24,678",
    image: "/jeep-wrangler-off-road-suv.jpg",
  },
]
